/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static view.Form.role;
import static view.Form.nim;
import static view.Form.nama;
import static view.Form.kelas;
import static view.Edit.role;
import static view.Edit.nim;
import static view.Edit.nama;
import static view.Edit.kelas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.Database;

/**
 *
 * @author Lenovo
 */
public class Jadwal extends javax.swing.JFrame implements Runnable {
    private String nim;
    private String role;
    private String nama;
    private String kelas;
    
    Thread T;
    boolean directionRight = true;
    int x, y, xx, xy;

    /**
     * Creates new form Info
     */
    public Jadwal() {
        
        initComponents();
        loadTableData();
        setLocationRelativeTo(null);
        
        x = labelFooter2.getX();
        y = labelFooter2.getY();
        T = new Thread(this);
        T.start();
    }
   
    
    @Override
    public void run(){
        while (true) {
            if (directionRight) {
                x++;
                if (x >= jPanel3.getWidth() - labelFooter2.getWidth()) {
                    directionRight = false;
                }
            } else {
                x--;
                if (x <= 0) {
                    directionRight = true;
                }
            }
            labelFooter2.setLocation(x, y);
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(Home2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void loadTableData(){
        DefaultTableModel dtm = (DefaultTableModel) roleTable.getModel();
        refreshTable(dtm);
    }  
    
    private void refreshTable(DefaultTableModel dtm) {
        // Refresh tabel
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }

            try (Connection conn = Database.connect()) {
                String sql = "SELECT role, ruangan, waktu FROM jadwal";
                try (PreparedStatement stmt = conn.prepareStatement(sql);
                     ResultSet rs = stmt.executeQuery()) {

                    // Isi tabel
                    while (rs.next()) {
                        String role = rs.getString("role");
                        String ruangan = rs.getString("ruangan");
                        String waktu = rs.getString("waktu");
                        dtm.addRow(new Object[]{role, ruangan, waktu});
                    }
                }
            } catch (SQLException ex) {
                System.err.println(ex);
                JOptionPane.showMessageDialog(this, "Gagal mengambil data", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();
        buttonDaftar = new javax.swing.JButton();
        buttonPendaftar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleTable = new javax.swing.JTable();
        buttonUbah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelFooter2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_xbar.jpeg"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, 100, 86));

        labelLogin1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        labelLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin1.setText("JOIN X-BAR");
        jPanel4.add(labelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 117, 127, -1));

        buttonLogout.setBackground(new java.awt.Color(255, 51, 51));
        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setText("LOGOUT");
        buttonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(buttonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 346, 88, 26));

        buttonHome.setBackground(new java.awt.Color(0, 0, 0));
        buttonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHome.setForeground(new java.awt.Color(255, 255, 255));
        buttonHome.setText("HOME");
        buttonHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        jPanel4.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 155, 88, 26));

        buttonDaftar.setBackground(new java.awt.Color(0, 0, 0));
        buttonDaftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDaftar.setForeground(new java.awt.Color(255, 255, 255));
        buttonDaftar.setText("JADWAL");
        buttonDaftar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarActionPerformed(evt);
            }
        });
        jPanel4.add(buttonDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 187, 88, 26));

        buttonPendaftar.setBackground(new java.awt.Color(0, 0, 0));
        buttonPendaftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPendaftar.setForeground(new java.awt.Color(255, 255, 255));
        buttonPendaftar.setText("PENDAFTAR");
        buttonPendaftar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonPendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPendaftarActionPerformed(evt);
            }
        });
        jPanel4.add(buttonPendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 219, 88, 26));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setBackground(new java.awt.Color(102, 204, 255));
        jLabel11.setFont(new java.awt.Font("Bernard MT Condensed", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-info-27.png"))); // NOI18N
        jLabel11.setText("JADWAL   SELEKSI");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonClose.setBackground(new java.awt.Color(255, 51, 51));
        buttonClose.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonClose.setText("X");
        buttonClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        minimize.setText("-");
        minimize.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose)
                    .addComponent(jLabel11)
                    .addComponent(minimize))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roleTable.setBackground(new java.awt.Color(204, 255, 255));
        roleTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        roleTable.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        roleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posisi", "Ruangan", "Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(roleTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 391, 120));

        buttonUbah.setBackground(new java.awt.Color(51, 255, 51));
        buttonUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUbah.setText("UBAH JADWAL");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel2.add(buttonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_bg.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 350));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelFooter2.setBackground(new java.awt.Color(51, 204, 255));
        labelFooter2.setFont(new java.awt.Font("Bernard MT Condensed", 2, 10)); // NOI18N
        labelFooter2.setForeground(new java.awt.Color(255, 255, 255));
        labelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFooter2.setText("Copyright © by Samuel Marvelius Sianturi");
        labelFooter2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(labelFooter2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelFooter2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0); // close window
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        this.setState(1); // minimize window
    }//GEN-LAST:event_minimizeActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Berhasil Logout!","LOGOUT SUCCESS",JOptionPane.INFORMATION_MESSAGE);
        // menuju ke halaman login
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:

        // menuju ke home
        Admin hm = new Admin();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftarActionPerformed
        // TODO add your handling code here:
        // menuju ke jadwal
        Jadwal fm2 = new Jadwal();
        fm2.setVisible(true);
        fm2.pack();
        fm2.setLocationRelativeTo(null);
        fm2.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonDaftarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void buttonPendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPendaftarActionPerformed
        // TODO add your handling code here:
        //masuk ke halaman tabel
        Tabel tabel = new Tabel();
        tabel.setVisible(true);
        tabel.pack();
        tabel.setLocationRelativeTo(null);
        tabel.setDefaultCloseOperation(Home2.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonPendaftarActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        
        
        DefaultTableModel dtm = (DefaultTableModel) roleTable.getModel();
        int selectedRow = roleTable.getSelectedRow();
            if (selectedRow >= 0) {
                String role = (String) dtm.getValueAt(selectedRow, 0);
                String ruangan = (String) dtm.getValueAt(selectedRow, 1);
                String waktu = (String) dtm.getValueAt(selectedRow, 2);

                // ke halaman edit
                Edit2 fm2 = new Edit2(role, ruangan, waktu);
                fm2.setVisible(true);
                fm2.pack();
                fm2.setLocationRelativeTo(null);
                fm2.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Tolong pilih jadwal yang ingin diubah", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_buttonUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Info().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Info().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDaftar;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPendaftar;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFooter2;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JButton minimize;
    private javax.swing.JTable roleTable;
    // End of variables declaration//GEN-END:variables

}