/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.*;
import model.Database;
import controller.Pendaftaran;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    public static String username;
    public static String password;
    private Pendaftaran pendaftaran;
    
    int xx, xy;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Aplikasi JOIN X-BAR");
        setLocationRelativeTo(null);
        pendaftaran = new Pendaftaran();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        labelFailed = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        labelRegister = new javax.swing.JLabel();
        buttonRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();
        minimize = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFailed.setForeground(new java.awt.Color(255, 51, 51));
        labelFailed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(labelFailed, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 460, 308, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername.setText("Username:");
        jPanel2.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 209, -1, -1));

        fieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUsernameFocusLost(evt);
            }
        });
        fieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsernameActionPerformed(evt);
            }
        });
        fieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldUsernameKeyTyped(evt);
            }
        });
        jPanel2.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 225, 194, 24));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setText("Password:");
        labelPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                labelPasswordFocusGained(evt);
            }
        });
        jPanel2.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 261, -1, -1));

        fieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPasswordFocusLost(evt);
            }
        });
        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        fieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 277, 194, 24));

        buttonLogin.setBackground(new java.awt.Color(102, 204, 255));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 313, 194, 33));

        labelRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRegister.setText("Belum punya akun?");
        jPanel2.add(labelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 388, -1, -1));

        buttonRegister.setBackground(new java.awt.Color(204, 204, 204));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(51, 51, 255));
        buttonRegister.setText("Register");
        buttonRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 383, 71, 26));

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_xbar.jpeg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 30, 368, 96));

        labelLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin1.setText("LOGIN");
        jPanel2.add(labelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 178, 374, -1));

        labelLogin.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("JOIN X-BAR");
        jPanel2.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 128, 374, -1));

        buttonClose.setBackground(new java.awt.Color(255, 51, 51));
        buttonClose.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonClose.setText("X");
        buttonClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1, 45, -1));

        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        minimize.setText("-");
        minimize.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 1, 45, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // menuju ke register
            Register rg = new Register();
            rg.setVisible(true);
            rg.pack();
            rg.setLocationRelativeTo(null);
            rg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
            
            this.dispose();
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void labelPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelPasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPasswordFocusGained

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
 
        if (fieldPassword.getText().equals("") || fieldUsername.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "Username dan Password harus diisi!","WARNING",JOptionPane.WARNING_MESSAGE);
        } else if ( fieldUsername.getText().equals("Admin") && fieldPassword.getText().equals("admin123") ) {
            JOptionPane.showMessageDialog(null,"Berhasil login sebagai admin!","LOGIN SUCCESS",JOptionPane.INFORMATION_MESSAGE);
            // menuju ke page admin
            Admin adm = new Admin();
            adm.setVisible(true);
            adm.pack();
            adm.setLocationRelativeTo(null);
            adm.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
            this.dispose();
        }
        else {
            username = fieldUsername.getText();
            password = fieldPassword.getText();

            try {
                Connection conn = Database.connect();
                
                String sql = "SELECT id FROM akun WHERE username = ? AND password = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, username);
                pstmt.setString(2, password);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    int id = rs.getInt("id");
                    // Check apakah nilai id ada di tabel member
                    sql = "SELECT nim, nama, kelas, role FROM member WHERE id = ?";
                    PreparedStatement stmt = conn.prepareStatement(sql);
                    stmt.setInt(1, id);
                    ResultSet rsMember = stmt.executeQuery();
                    
                    if (rsMember.next()) {
                        String nim = rsMember.getString("nim");
                        String nama = rsMember.getString("nama");
                        String kelas = rsMember.getString("kelas");
                        String role = rsMember.getString("role");
                        JOptionPane.showMessageDialog(null,"Berhasil login!","LOGIN SUCCESS",JOptionPane.INFORMATION_MESSAGE);

                        // menuju ke home2
                        Home2 hm = new Home2(role, nim, nama, kelas);
                        hm.setVisible(true);
                        hm.pack();
                        hm.setLocationRelativeTo(null);
                        hm.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        
                        JOptionPane.showMessageDialog(null,"Berhasil login!","LOGIN SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                        // menuju ke home
                        Home hm = new Home();
                        hm.setVisible(true);
                        hm.pack();
                        hm.setLocationRelativeTo(null);
                        hm.setDefaultCloseOperation(Form.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                    rsMember.close();
                    stmt.close();
                }   
                   else {
                    JOptionPane.showMessageDialog(null, "Username atau password tidak valid!", "LOGIN FAILED", JOptionPane.ERROR_MESSAGE);
                }

                rs.close();
                pstmt.close();
                conn.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void fieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsernameActionPerformed

    private void fieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUsernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsernameFocusGained

    private void fieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordFocusGained

    private void fieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsernameFocusLost

    private void fieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPasswordFocusLost
        // TODO add your handling code here:       
    }//GEN-LAST:event_fieldPasswordFocusLost

    private void fieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUsernameKeyTyped
        // TODO add your handling code here:
    // Mendapatkan karakter yang diketik
    char c = evt.getKeyChar();

    // Memeriksa apakah panjang teks melebihi 20 atau karakter bukan huruf/angka
    if (fieldUsername.getText().length() >= 20 || !Character.isLetterOrDigit(c)) {
        evt.consume(); // Membatalkan aksi jika tidak sesuai kriteria
    }
    }//GEN-LAST:event_fieldUsernameKeyTyped

    private void fieldPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPasswordKeyTyped
        // TODO add your handling code here:
    // Mendapatkan karakter yang diketik
    char c = evt.getKeyChar();

    // Memeriksa apakah panjang teks melebihi 20 atau karakter bukan huruf/angka
    if (fieldPassword.getText().length() >= 20 || !Character.isLetterOrDigit(c)) {
        evt.consume(); // Membatalkan aksi jika tidak sesuai kriteria
    }
    }//GEN-LAST:event_fieldPasswordKeyTyped

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0); // close window
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        this.setState(1); // minimize window
    }//GEN-LAST:event_minimizeActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelFailed;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables

}