/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import exporter.CSVExporter;
import controller.Email;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.*;
import model.Database;
import controller.Pendaftaran;

/**
 *
 * @author Lenovo
 */
public class Register extends javax.swing.JFrame {

    public static String email;
    public static String username;
    public static String password;
    int xx, xy;
    private Email mail;
    
    public Register() {
        initComponents();
        mail = new Email();
        setTitle("Aplikasi JOIN X-BAR");
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        fieldPassword1 = new javax.swing.JPasswordField();
        labelWarning = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelUsername1 = new javax.swing.JLabel();
        labelPassword1 = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        buttonRegister = new javax.swing.JButton();
        fieldEmail = new javax.swing.JTextField();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword2 = new javax.swing.JPasswordField();
        fieldConfirmPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        minimize = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        labelRegister = new javax.swing.JLabel();
        Login = new javax.swing.JButton();

        labelPassword.setText("Password:");

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelUsername.setText("Username:");

        fieldPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassword1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(35550, 35550));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelWarning.setForeground(new java.awt.Color(255, 51, 0));
        labelWarning.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(labelWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 0, 113, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Email:");

        labelUsername1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername1.setText("Username:");

        labelPassword1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword1.setText("Password:");

        labelConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConfirmPassword.setText("Konfirmasi Password:");

        buttonRegister.setBackground(new java.awt.Color(102, 204, 255));
        buttonRegister.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        fieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldEmailFocusLost(evt);
            }
        });
        fieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldEmailKeyTyped(evt);
            }
        });

        fieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUsernameFocusLost(evt);
            }
        });
        fieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldUsernameKeyTyped(evt);
            }
        });

        fieldPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPassword2ActionPerformed(evt);
            }
        });
        fieldPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldPassword2KeyTyped(evt);
            }
        });

        fieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldConfirmPasswordActionPerformed(evt);
            }
        });
        fieldConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldConfirmPasswordKeyTyped(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_xbar.jpeg"))); // NOI18N

        labelLogin.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("JOIN X-BAR");

        labelLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin1.setText("REGISTER");

        minimize.setBackground(new java.awt.Color(204, 204, 204));
        minimize.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        minimize.setText("-");
        minimize.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });

        buttonClose.setBackground(new java.awt.Color(255, 51, 51));
        buttonClose.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonClose.setText("X");
        buttonClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        labelRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRegister.setText("Sudah punya akun?");

        Login.setBackground(new java.awt.Color(204, 204, 204));
        Login.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(51, 51, 255));
        Login.setText("Login");
        Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword1)
                            .addComponent(labelUsername1)
                            .addComponent(labelConfirmPassword)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName)
                            .addComponent(fieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimize)
                    .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogin)
                .addGap(20, 20, 20)
                .addComponent(labelLogin1)
                .addGap(12, 12, 12)
                .addComponent(labelName)
                .addGap(0, 0, 0)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsername1)
                .addGap(0, 0, 0)
                .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPassword1)
                .addGap(0, 0, 0)
                .addComponent(fieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelConfirmPassword)
                .addGap(0, 0, 0)
                .addComponent(fieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegister)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

    }//GEN-LAST:event_buttonLoginActionPerformed

    private void fieldPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassword1ActionPerformed

    private void fieldPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPassword2ActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // cek isi username dan password
        if (fieldUsername.getText().equals("") || fieldPassword2.getText().equals("") || fieldEmail.getText().equals("") 
               || fieldConfirmPassword.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Semua harus diisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (!fieldPassword2.getText().equals(fieldConfirmPassword.getText()) ) {
            JOptionPane.showMessageDialog(this, "Password dan konfirmasi password tidak cocok", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        else {
            String email = fieldEmail.getText().trim();
            String username = fieldUsername.getText().trim();
            String password = new String(fieldPassword2.getPassword()).trim();
            
            try {
                Connection conn = Database.connect();
                String sql = "INSERT INTO akun (email, username, password) VALUES (?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, email);
                pstmt.setString(2, username);
                pstmt.setString(3, password);
                pstmt.executeUpdate();

                // Kirim email konfirmasi registrasi
                new Thread(() -> {
                    mail.sendConfirmationEmail(email);
                }).start();

                pstmt.close();
                conn.close();

                JOptionPane.showMessageDialog(this, "Registrasi akun baru sukses! Tolong cek email anda.","REGISTRATION SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                // menuju ke halaman login
                Login lg = new Login();
                lg.setVisible(true);
                lg.pack();
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);

                // tutup pop up registrasi
                this.dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Registrasi Gagal!\n Mohon ganti email atau username.", "FAILED", JOptionPane.ERROR_MESSAGE);
            }        
        } 
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void fieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldConfirmPasswordActionPerformed

    private void fieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusLost
       
    }//GEN-LAST:event_fieldEmailFocusLost

    private void fieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUsernameFocusLost
        
    }//GEN-LAST:event_fieldUsernameFocusLost

    private void fieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailKeyTyped

    private void fieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldUsernameKeyTyped
        // TODO add your handling code here:
        // Mendapatkan karakter yang diketik
        char c = evt.getKeyChar();

        // Memeriksa apakah panjang teks melebihi 20 atau karakter bukan huruf/angka
        if (fieldUsername.getText().length() >= 20 || !Character.isLetterOrDigit(c)) {
            evt.consume(); // Membatalkan aksi jika tidak sesuai kriteria
        }
    }//GEN-LAST:event_fieldUsernameKeyTyped

    private void fieldPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassword2KeyTyped
        // TODO add your handling code here:
        // Mendapatkan karakter yang diketik
        char c = evt.getKeyChar();

        // Memeriksa apakah panjang teks melebihi 20 atau karakter bukan huruf/angka
        if (fieldPassword2.getText().length() >= 20 || !Character.isLetterOrDigit(c)) {
            evt.consume(); // Membatalkan aksi jika tidak sesuai kriteria
        }
    }//GEN-LAST:event_fieldPassword2KeyTyped

    private void fieldConfirmPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldConfirmPasswordKeyTyped
        // TODO add your handling code here:
        // Mendapatkan karakter yang diketik
        char c = evt.getKeyChar();

        // Memeriksa apakah panjang teks melebihi 20 atau karakter bukan huruf/angka
        if (fieldConfirmPassword.getText().length() >= 20 || !Character.isLetterOrDigit(c)) {
            evt.consume(); // Membatalkan aksi jika tidak sesuai kriteria
        }
    }//GEN-LAST:event_fieldConfirmPasswordKeyTyped

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        this.setState(1); // minimize window
    }//GEN-LAST:event_minimizeActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0); // close window
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // menuju ke halaman login
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JPasswordField fieldConfirmPassword;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldPassword1;
    private javax.swing.JPasswordField fieldPassword2;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables

}